name: pokedex_modular
description: "A new Flutter project. Created by Slidy"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cached_network_image: ^2.0.0
  md2_tab_indicator: ^1.0.2
  flutter_staggered_animations: ^0.1.2
  sliding_sheet: ^0.3.1
  simple_animations: ^1.3.11
  dio: ^3.0.9
  flutter_mobx: ^1.1.0
  mobx: ^1.1.1
  flutter_modular: ^1.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^4.1.1
  mobx_codegen: ^1.0.3
  build_runner: ^1.8.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/pokeball_dark.png
    - assets/images/pokeball.png

  fonts:
    - family: PokemonFont
      fonts:
        - asset: assets/fonts/ProductSans-Regular.ttf
        - asset: assets/fonts/ProductSans-Bold.ttf
          weight: 700

scripts:
  build: flutter pub run build_runner build --delete-conflicting-outputs
  clean: flutter pub run build_runner clean
  watch: flutter pub run build_runner watch --delete-conflicting-outputs