name: pokedex
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  simple_animations: ^1.3.11
  intl: ^0.16.1
  flutter_icons: ^1.0.0+1
  sliding_sheet: ^0.2.10
  flutter_staggered_animations: ^0.1.2
  md2_tab_indicator: ^1.0.2
  cached_network_image: ^2.0.0
  flutter_mobx: ^1.1.0
  mobx: ^1.1.1
  dio: ^3.0.9
  rxdart: ^0.23.1
  flutter_modular: ^1.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  mobx_codegen: ^1.0.3
  build_runner: ^1.8.0
  mockito: ^4.1.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/pokeball_dark.png
    - assets/images/pokeball.png

  fonts:
    - family: PokemonFont
      fonts:
        - asset: assets/fonts/ProductSans-Regular.ttf
        - asset: assets/fonts/ProductSans-Bold.ttf
          weight: 700

scripts:
  build: flutter pub run build_runner build --delete-conflicting-outputs
  clean: flutter pub run build_runner clean
  watch: flutter pub run build_runner watch --delete-conflicting-outputs